### Get All Stadiums
GET https://localhost:8443/api/v1/stadiums
Content-Type: application/json

### Get Stadium by Name
GET https://localhost:8443/api/v1/stadiums/Petco Park
Content-Type: application/json

### Get Non Existent Stadium
GET https://localhost:8443/api/v1/stadiums/Stadium1
Content-Type: application/json

### Add a Picture to a Stadium
POST https://localhost:8443/api/v1/stadiums/Petco Park/pictures
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Chief1.png"
Content-Type: image/png

< ./Chief1.png
--WebAppBoundary--

### Delete a picture of a Stadium
DELETE https://localhost:8443/api/v1/stadiums/Petco Park/pictures?publicId=n83mdgmpa9jmw1rfwpx6