### Get All Teams
GET https://diamond-insights.up.railway.app/api/v1/teams?page=0&size=10
Accept: application/json

### Get Available Teams
GET https://diamond-insights.up.railway.app/api/v1/teams/available?page=0&size=10
Accept: application/json

### Get Standings
GET https://diamond-insights.up.railway.app/api/v1/teams/standings
Accept: application/json

### Get Team Information
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees
Accept: application/json

### Get Non Existent Team Information
GET https://diamond-insights.up.railway.app/api/v1/teams/Team1
Accept: application/json

### Get Rival Teams
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees/rivals
Accept: application/json

### Get Wins of a Single Rival
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees/analytics/wins-per-rival?rivalTeamNames=San Francisco Giants
Accept: application/json

### Get Wins of Multiple Rivals
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees/analytics/wins-per-rival?rivalTeamNames=San Francisco Giants, Seattle Mariners
Accept: application/json

### Get Wins with Non Rivals
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees/analytics/wins-per-rival?rivalTeamNames=
Accept: application/json

### Get Wins With Fix Team = Rival Team
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees/analytics/wins-per-rival?rivalTeamNames=New York Yankees
Accept: application/json

### Get Runs Stats
GET https://diamond-insights.up.railway.app/api/v1/teams/analytics/runs-per-rival?teams=New York Yankees, Houston Astros, Los Angeles Dodgers, Toronto Blue Jays
Accept: application/json

### Get Win Distribution
GET https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees/analytics/win-distribution
Accept: application/json

### Temp
POST https://diamond-insights.up.railway.app/api/v1/teams/analytics/hydrate
Accept: application/json

### Refresh Standings
POST https://diamond-insights.up.railway.app/api/v1/teams/sync
Accept: application/json

### Get Historic Ranking
GET https://diamond-insights.up.railway.app/api/v1/teams/analytics/historic-ranking?teams=New York Yankees, Boston Red Sox, Los Angeles Dodgers
Accept: application/json

### Get Historic Ranking
GET https://diamond-insights.up.railway.app/api/v1/teams/analytics/historic-ranking?teams=New York Yankees&dateFrom=2026-04-01
Accept: application/json

### Update Team with city, championships and general information
PATCH https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees
Content-Type: application/json

{
  "city": "Perú",
  "newChampionship": 2025,
  "newInfo": "New Info Test",
  "newStadiumName": "Shippet Stadium"
}

### Update Team with only one field
PATCH https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees
Content-Type: application/json

{
  "city": "Memphis"
}

### Update team with an invalid stadium. An invalid stadium is one that already has a team assigned.
PATCH https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees
Content-Type: application/json

{
  "newStadiumName": "Petco Park"
}

### Update Team with a non existent stadium
PATCH https://diamond-insights.up.railway.app/api/v1/teams/New York Yankees
Content-Type: application/json

{
  "newStadiumName": "Stadium1"
}

### Update a non existent Team
PATCH https://diamond-insights.up.railway.app/api/v1/teams/Team1
Content-Type: application/json

{
  "city": "Perú",
  "newChampionship": 2025,
  "newInfo": "New Info Test"
}