### Get All Teams
GET https://localhost:8443/api/v1/teams
Content-Type: application/json

### Get Standings
GET https://localhost:8443/api/v1/teams/standings
Content-Type: application/json

### Get Team Information
GET https://localhost:8443/api/v1/teams/Cincinnati Reds
Content-Type: application/json

### Get Non Existent Team Information
GET https://localhost:8443/api/v1/teams/Team1
Content-Type: application/json