### Get Matches of the day
GET https://localhost:8443/api/v1/matches/today
Content-Type: application/json

### Get All Matches of the 2026 Season
GET https://localhost:8443/api/v1/mlb/schedule?from=2026-03-01&to=2026-10-31
Content-Type: application/json

### Get Home Matches of a certain team
GET https://localhost:8443/api/v1/matches/home/Cincinnati Reds
Content-Type: application/json

### Get Away Matches of a certain team
GET https://localhost:8443/api/v1/matches/away/Cincinnati Reds
Content-Type: application/json