name: Complete Quality Control

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Backend Build CQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "22"

      - name: Server Compile
        run: mvn clean compile
        working-directory: ./backend

  backend-unit-tests:
    name: Unit Tests Backend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Unit Tests
        run: mvn test -Dsurefire.excludes="**/integration/**,**/e2e/**"
        working-directory: ./backend

  backend-integration-tests:
    name: Integration Tests Backend
    runs-on: ubuntu-latest
    needs: backend-unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Integration Tests
        run: mvn test -Dsurefire.excludes="**/unit/**,**/e2e/**"
        working-directory: ./backend

  backend-e2e-tests:
    name: E2E Tests Backend
    runs-on: ubuntu-latest
    needs: backend-integration-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run E2E Tests
        run: mvn test -Dsurefire.excludes="**/integration/**,**/unit/**"
        working-directory: ./backend

  build-frontend:
    name: Frontend Build CQ
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js 22 Configuration
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Install Angular Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Frontend Compile
        run: npm run build -- --configuration production
        working-directory: ./frontend

  frontend-unit-tests:
    name: Unit Tests Frontend
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
        
      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: ./frontend

  frontend-integration-tests:
    name: Integration Tests Frontend
    runs-on: ubuntu-latest
    needs: frontend-unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run Integration Tests
        run: npm run test:integration
        working-directory: ./frontend

  frontend-e2e-tests:
    name: E2E Tests Frontend
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Serve Angular in background
        run: npx ng serve --port 4200 --host 0.0.0.0 &
        working-directory: ./frontend
      - name: Wait for Angular to be ready
        run: npx wait-on http://localhost:4200
        working-directory: ./frontend
      - name: Run Cypress E2E Tests
        run: npx cypress run --config baseUrl=http://localhost:4200
        working-directory: ./frontend
